package com.nt.advjava;

public class Procedure_Assignment1 {
	/*
	CREATE TABLE "SHA"."EMPDETAILS77" 
	   (	"EID" NUMBER, 
		"ENAME" VARCHAR2(20 BYTE), 
		"EDESIG" VARCHAR2(20 BYTE), 
		"BSAL" FLOAT(126), 
		"TSAL" FLOAT(126)
	   )
	   CREATE TABLE "SHA"."EMPADD77" 
   (	"EID" NUMBER NOT NULL ENABLE, 
	"H_NO" VARCHAR2(20 BYTE), 
	"STREET_NAME" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER
   )
	  CREATE TABLE "SHA"."EMP_CONTACT77" 
   (	"EID" NUMBER, 
	"EMAILID" VARCHAR2(20 BYTE), 
	"MOBILENO" NUMBER, 
	"PHOTO" BLOB
   )  
   Procedure
   
   create or replace procedure EMP_ACCOUNT77
   (EID NUMBER, ENAME VARCHAR2, EDESIG VARCHAR2, BSAL FLOAT, TSAL FLOAT
   H_NO VARCHAR2, STREET_NAME VARCHAR2, CITY VARCHAR2, PINCODE NUMBER
   EMAILID VARCHAR2, MOBILENO NUMBER, PHOTO BLOB) IS BEGIN
   INSERT INTO EMPDETAILS77 VALUES(EID,ENAME,EDESIG,BSAL,TSAL);
   INSERT INTO EMPADD77 VALUES(EID, H_NO, STREET_NAME, CITY, PINCODE);
   INSERT INTO EMP_CONTACT77 VALUES(EID, EMAILID, MOBILENO, CITY, PHOTO);
	 END 
	   */
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
